=== nikolausn/metadata/final_project/combined_simple_v3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="AuthorType">
        <xs:sequence>
            <xs:element ref="Author" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ObjectiveType">
        <xs:sequence>
            <xs:element name="UsageFeature" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="Description" type="xs:string"/>
            <xs:element name="Page" type="xs:int" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PublicationIdentifierType">
        <xs:sequence>
            <xs:element name="IdentifierType" type="xs:string"/>
            <xs:element name="IdentifierValue" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RepositoryType">
        <xs:sequence>
            <xs:element name="RepoType" type="xs:string"/>
            <xs:element name="URL" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AuthorsType">
        <xs:sequence>
            <xs:element name="AuthorUrl" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FeatureType">
        <xs:sequence>
            <xs:element name="FeatureName" type="xs:string"/>
            <xs:element name="Description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SoftwareIdentifierType">
        <xs:complexContent>
            <xs:extension base="GenericIdentifierType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="SoftwareCitationType">
        <xs:sequence>
            <xs:element name="PublicationIdentifier" type="PublicationIdentifierType"/>
            <xs:element maxOccurs="unbounded" name="SoftwareUsage">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="SoftwareIdentifierType">
                            <xs:sequence>
                                <xs:element ref="Objective"/>
                            </xs:sequence>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SoftwareType">
        <xs:sequence>
            <xs:element ref="Software" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AuthorIdentifierType">
        <xs:sequence>
            <xs:element name="Identifier" type="GenericIdentifierType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AuthorNameType">
        <xs:sequence>
            <xs:element minOccurs="1" name="FirstName" type="xs:string"/>
            <xs:element minOccurs="0" name="MidleName" type="xs:string"/>
            <xs:element minOccurs="0" name="LastName" type="xs:string"/>
            <xs:element name="RecordedDate" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AffiliationIdentifierType">
        <xs:sequence>
            <xs:element name="Identifier" type="GenericIdentifierType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GenericIdentifierType">
        <xs:sequence>
            <xs:element name="IdentifierType" type="xs:string"/>
            <xs:element name="IdentifierValue" type="xs:string"/>
            <xs:element minOccurs="0" name="RecordedDate" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PublicationType">
        <xs:sequence>
            <xs:element ref="Publication" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="SoftwareCitation" type="SoftwareCitationType"> </xs:element>
    <xs:element name="SoftwareCitationRoot">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="SoftwareCitationList"/>
                <xs:element ref="PublicationList"/>
                <xs:element ref="AuthorList"/>
                <xs:element ref="SoftwareList"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Publication">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PublicationTitle" type="xs:string"/>
                <xs:element name="PublicationIdentifiers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PublicationIdentifier"
                                type="PublicationIdentifierType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Author" type="AuthorIdentifierType"
                                maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="SoftwareCitationList">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="SoftwareCitation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="SoftwareList" type="SoftwareType"/>
    <xs:element name="AuthorList" type="AuthorType"/>
    <xs:element name="PublicationList" type="PublicationType"/>
    <xs:element name="Software">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SoftwareNames">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SoftwareName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="SoftwareIdentifier" type="GenericIdentifierType"/>
                <xs:element name="SoftwarePlatforms">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PlatformName" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Repository" type="RepositoryType"/>
                <xs:element name="Version" type="xs:string"/>
                <xs:element name="Features">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Feature" type="FeatureType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Contributors" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Contributor" type="AuthorIdentifierType"
                                maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Author">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AuthorIdentifiers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="AuthorIdentifier"
                                type="AuthorIdentifierType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="AuthorNames">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="AuthorName" type="AuthorNameType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Affiliations" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="AffiliationIdentifier"
                                type="AffiliationIdentifierType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Objective" type="ObjectiveType"/>
</xs:schema>

=== nikolausn/metadata/final_project/Untitled2.xml
<?xml version="1.0" encoding="UTF-8"?>
<SoftwareCitationRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="combined_simple_v3.xsd">
    <SoftwareCitationList>
        <SoftwareCitation>
            <PublicationIdentifier>
                <IdentifierType>DOI</IdentifierType>
                <IdentifierValue>10.1145/2756406.2756929</IdentifierValue>
            </PublicationIdentifier>
            <SoftwareUsage>
                <IdentifierType>URL</IdentifierType>
                <IdentifierValue>https://www.inphoproject.org</IdentifierValue>
                <Objective>
                    <UsageFeature>Visualization</UsageFeature>
                    <Description>Print Screen of the Website, Tools description</Description>
                    <Page>1</Page>
                </Objective>
            </SoftwareUsage>
        </SoftwareCitation>
        <SoftwareCitation>
            <PublicationIdentifier>
                <IdentifierType>DOI</IdentifierType>
                <IdentifierValue>10.1007/s11229-009-9659-9</IdentifierValue>
            </PublicationIdentifier>
            <SoftwareUsage>
                <IdentifierType>URL</IdentifierType>
                <IdentifierValue>https://www.inphoproject.org</IdentifierValue>
                <Objective>
                    <UsageFeature>Figure</UsageFeature>
                    <Description>View of InPhO interface showing crosslinks (@) from philosophy of cognitive science to other topics. SEP thinker icons to the left of terms indicate links to Stanford Encyclopedia articles, while the ‘SEP’, ‘Noesis’, ‘Scholar’ links provide direct access to the search engines using a query that is composed of that term plus its superordinate category</Description>
                    <Page>1</Page>
                </Objective>
            </SoftwareUsage>
        </SoftwareCitation>
    </SoftwareCitationList>
    <PublicationList>
        <Publication>
            <PublicationTitle>Topic Exploration with the HTRC Data Capsule for Non-Consumptive Research</PublicationTitle>
            <PublicationIdentifiers>
                <PublicationIdentifier>
                    <IdentifierType>DOI</IdentifierType>
                    <IdentifierValue>10.1145/2756406.2756929</IdentifierValue>
                </PublicationIdentifier>
            </PublicationIdentifiers>
            <Authors>
                <Author>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>1</IdentifierValue>
                    </Identifier>                    
                </Author>     
                <Author>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>2</IdentifierValue>
                    </Identifier>                    
                </Author>    
            </Authors>
        </Publication>
        <Publication>
            <PublicationTitle>From encyclopedia to ontology: toward dynamic representation of the discipline of philosophy</PublicationTitle>
            <PublicationIdentifiers>
                <PublicationIdentifier>
                    <IdentifierType>DOI</IdentifierType>
                    <IdentifierValue>10.1007/s11229-009-9659-9</IdentifierValue>
                </PublicationIdentifier>
            </PublicationIdentifiers>
            <Authors>
                <Author>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>3</IdentifierValue>
                    </Identifier>                    
                </Author>     
                <Author>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>4</IdentifierValue>
                    </Identifier>                    
                </Author>
                <Author>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>5</IdentifierValue>
                    </Identifier>                    
                </Author>    
            </Authors>
        </Publication>
    </PublicationList>
    <AuthorList>
        <Author>
            <AuthorIdentifiers>
                <AuthorIdentifier>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>1</IdentifierValue>
                        <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                    </Identifier>
                </AuthorIdentifier>
            </AuthorIdentifiers>
            <AuthorNames>
                <AuthorName>
                    <FirstName>Jaimie</FirstName>
                    <LastName>Murdock</LastName>
                    <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                </AuthorName>
            </AuthorNames>     
        </Author>
        <Author>
            <AuthorIdentifiers>
                <AuthorIdentifier>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>2</IdentifierValue>
                        <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                    </Identifier>
                </AuthorIdentifier>
            </AuthorIdentifiers>
            <AuthorNames>
                <AuthorName>
                    <FirstName>Jiaan</FirstName>
                    <LastName>Zeng</LastName>
                    <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                </AuthorName>
            </AuthorNames>
        </Author>
        <Author>
            <AuthorIdentifiers>
                <AuthorIdentifier>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>3</IdentifierValue>
                        <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                    </Identifier>
                </AuthorIdentifier>
            </AuthorIdentifiers>
            <AuthorNames>
                <AuthorName>
                    <FirstName>Cameron</FirstName>
                    <LastName>Buckner</LastName>
                    <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                </AuthorName>
            </AuthorNames>
        </Author>
        <Author>
            <AuthorIdentifiers>
                <AuthorIdentifier>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>4</IdentifierValue>
                        <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                    </Identifier>
                </AuthorIdentifier>
            </AuthorIdentifiers>
            <AuthorNames>
                <AuthorName>
                    <FirstName>Mathias</FirstName>
                    <LastName>Niepert</LastName>
                    <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                </AuthorName>
            </AuthorNames>
        </Author>
        <Author>
            <AuthorIdentifiers>
                <AuthorIdentifier>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>5</IdentifierValue>
                        <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                    </Identifier>
                </AuthorIdentifier>
            </AuthorIdentifiers>
            <AuthorNames>
                <AuthorName>
                    <FirstName>Colin</FirstName>
                    <LastName>Allen</LastName>
                    <RecordedDate>2019-10-27T14:39:00</RecordedDate>
                </AuthorName>
            </AuthorNames>
        </Author>
    </AuthorList>
    <SoftwareList>
        <Software>
            <SoftwareNames>
                <SoftwareName>The InPhO Project</SoftwareName>
            </SoftwareNames>
            <SoftwareIdentifier>
                <IdentifierType>URL</IdentifierType>
                <IdentifierValue>https://www.inphoproject.org</IdentifierValue>
            </SoftwareIdentifier>
            <SoftwarePlatforms>
                <PlatformName>Python</PlatformName>
                <PlatformName>Javascript</PlatformName>
                <PlatformName>Jupyter Notebook</PlatformName>
            </SoftwarePlatforms>
            <Repository>
                <RepoType>Github</RepoType>
                <URL>https://github.com/inpho/</URL>
            </Repository>
            <Version></Version>
            <Features>
                <Feature>
                    <FeatureName>Topic Modeling</FeatureName>
                    <Description></Description>
                </Feature>
                <Feature>
                    <FeatureName>Data Mining</FeatureName>
                    <Description></Description>
                </Feature>
                <Feature>
                    <FeatureName>Searching</FeatureName>
                    <Description></Description>
                </Feature>
            </Features>
            <Contributors>
                <Contributor>
                    <Identifier>
                        <IdentifierType>local</IdentifierType>
                        <IdentifierValue>1</IdentifierValue>
                    </Identifier>             
                </Contributor>
            </Contributors>
        </Software>
    </SoftwareList>
</SoftwareCitationRoot>
